services:
  db-auth:
    image: postgres:17
    container_name: db-auth
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-auth-data:/var/lib/postgresql/data
      - ./001_create_users.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-auth-data:
    driver: local
